### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by aryan7tiwary** [Mega-Mewthree/BetterDiscordPlugins#107]
AutoStartRichPresence.plugin.js: Could not be compiled.

**Comment by aryan7tiwary** [comment]
AutoStartRichPresence.plugin.js: Could not be compiled.
    at Object.loadAddon (<anonymous>:4:190848)
    at Object.loadAddon (<anonymous>:4:228205)
    at FSWatcher.<anonymous> (<anonymous>:4:189109)

**Comment by Mega-Mewthree** [comment]
You did not download it correctly. Perhaps you downloaded an HTML page instead of the plugin.

**Comment by hh12github** [comment]
i just redownloaded it, 
Error: ENOENT: no such file or directory, lstat 'C:\Users\[my real name]\AppData\Local\DiscordPTB\app-1.0.1020\zlib'
    at Object.T [as realpathSync] (<anonymous>:4:346490)
    at Function.getFilePath (<anonymous>:4:347760)
    at Function._load (<anonymous>:4:347855)
    at <anonymous>:4:351046
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.loadAllAddons (<anonymous>:4:11637)
    at Object.initialize (<anonymous>:4:6059)
    at Object.initialize (<anonymous>:4:36059)
    at Object.startup (<anonymous>:4:396505)

**Comment by Taxrosdev** [comment]
Same file, But different because I am using Arch Linux
/usr/bin/zlib ENOENT

Theres a Dependency for some compression library called Zlib and its not installed
