### ISSUE TITLE
AutoStartRichPresence.plugin error

### ISSUE THREAD

**Issue by ExHermes** [Mega-Mewthree/BetterDiscordPlugins#161]
After today's discord update the plugin stopped working.

**Comment by kriskut08** [comment]
Yes, it really stopped working here is my error message:

`Error: ENOENT: no such file or directory, lstat '/usr/bin/zlib'
    at Object.D [as realpathSync] (<anonymous>:4:318891)
    at Function.getFilePath (<anonymous>:4:320147)
    at Function._load (<anonymous>:4:320242)
    at Function.o._load (<anonymous>:4:379728)
    at <anonymous>:4:323433
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at Object.loadAllAddons (<anonymous>:4:11607)
    at Object.initialize (<anonymous>:4:6257)
    at Object.initialize (<anonymous>:4:40368)
    at Object.startup (<anonymous>:4:376262)`

**Comment by aurkaxi** [comment]
hey devs ?

**Comment by hh12github** [comment]
is it because i installed on a ptb discord?

**Comment by RaulRDA** [comment]
> is it because i installed on a ptb discord?

No.
It doesn't work on any discord, it's outdated

**Comment by Miniontoby** [comment]
Please close this issue as the fix is inside:

https://github.com/Mega-Mewthree/BetterDiscordPlugins/issues/177#issuecomment-1664456294
