### ISSUE TITLE
Plugin could not be compiled

### ISSUE THREAD

**Issue by Skrblikos** [Mega-Mewthree/BetterDiscordPlugins#163]
Error: ENOENT: no such file or directory, lstat 'C:\Users\mel\AppData\Local\Discord\app-1.0.9006\zlib'
    at Object.D [as realpathSync] (<anonymous>:4:318891)
    at Function.getFilePath (<anonymous>:4:320147)
    at Function._load (<anonymous>:4:320242)
    at Function.o._load (<anonymous>:4:379728)
    at <anonymous>:4:323433
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at AsyncFunction.<anonymous> (<anonymous>:4:7353)

**Comment by kriskut08** [comment]
This also happens on linux

**Comment by ghost** [comment]
Plugins are broken, be patient instead of opening issues everyday....

**Comment by Zarq0** [comment]
Duplicate of #161
