### ISSUE TITLE
AutoStartRichPresence could not be compiled see console for more details

### ISSUE THREAD

**Issue by DaxiTheFloof** [Mega-Mewthree/BetterDiscordPlugins#167]
Error: ENOENT: no such file or directory, lstat 'C:\Users\User\AppData\Local\Discord\app-1.0.9007\zlib'
    at Object.T [as realpathSync] (<anonymous>:4:346490)
    at Function.getFilePath (<anonymous>:4:347760)
    at Function._load (<anonymous>:4:347855)
    at <anonymous>:4:351046
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at AsyncFunction.<anonymous> (<anonymous>:4:7155)

**Comment by Garciamk3g** [comment]
Have you been able to fix this? 

I've created a dummy [zlib] folder in this path [C:\Users\User\AppData\Local\Discord\app-1.0.9007] since the error states [Error: ENOENT: no such file or directory, lstat] now when trying to add the AutoStartRichPresence.plugin.js Inside the Better Discord Plugins folder I'm presented with a different Error.


NEW ERROR:

TypeError: I.slice is not a function
    at Function.resolveMainFile (<anonymous>:4:347466)
    at Function._load (<anonymous>:4:348056)
    at <anonymous>:4:351046
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at AsyncFunction.<anonymous> (<anonymous>:4:7155)

**Comment by SkuJin** [comment]
dev is dead

**Comment by fluffeliger** [comment]
cmon
