### ISSUE TITLE
An error was encountered while trying to load this plugin.

### ISSUE THREAD

**Issue by noxygalaxy** [Mega-Mewthree/BetterDiscordPlugins#172]
i trying to load plugin and that

An error was encountered while trying to load this plugin.

**Comment by YuniteeBots** [comment]
same, i got this error here:

Error: ENOENT: no such file or directory, lstat 'C:\Users\bagar\AppData\Local\Discord\app-1.0.9007\zlib' at Object.T [as realpathSync] (<anonymous>:4:346490) at Function.getFilePath (<anonymous>:4:347760) at Function._load (<anonymous>:4:347855) at <anonymous>:4:351046 at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18) at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6) at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5) at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3) at Object.requireAddon (<anonymous>:4:39192) at Object.loadAddon (<anonymous>:4:9163) at Object.loadAddon (<anonymous>:4:36864) at AsyncFunction.<anonymous> (<anonymous>:4:7155)


and the link for the Discord server does not work for support + the owner of this plugin does not accept Friend requests.

**Comment by ghost** [comment]
Same error

**Comment by ghost** [comment]
Error: ENOENT: no such file or directory, lstat 'C:\Users\calif\AppData\Local\Discord\app-1.0.9007\zlib'
    at Object.T [as realpathSync] (<anonymous>:4:346490)
    at Function.getFilePath (<anonymous>:4:347760)
    at Function._load (<anonymous>:4:347855)
    at <anonymous>:4:351046
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.reloadAddon (<anonymous>:4:10053)
    at AsyncFunction.<anonymous> (<anonymous>:4:7189)
