### ISSUE TITLE
An error was encountered while trying to load this plugin.

### ISSUE THREAD

**Issue by ghost** [Mega-Mewthree/BetterDiscordPlugins#174]
Error: ENOENT: no such file or directory, lstat 'C:\Users\calif\AppData\Local\Discord\app-1.0.9007\zlib'
    at Object.T [as realpathSync] (<anonymous>:4:346490)
    at Function.getFilePath (<anonymous>:4:347760)
    at Function._load (<anonymous>:4:347855)
    at <anonymous>:4:351046
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.reloadAddon (<anonymous>:4:10053)
    at AsyncFunction.<anonymous> (<anonymous>:4:7189)

**Comment by DaniCody** [comment]
I have the same issue. Weird

**Comment by InverterHub** [comment]
had the same

**Comment by BiBiska11** [comment]
same!!!

**Comment by White55Tiger** [comment]
same

**Comment by NihalGuruprasad** [comment]
same
