### ISSUE TITLE
On macOS, after putting your plugin into the plugin-folder of better discord

### ISSUE THREAD

**Issue by JTMG314** [Mega-Mewthree/BetterDiscordPlugins#176]
Error-message:

Error: ENOENT: no such file or directory, lstat '/zlib'
    at Object.T [as realpathSync] (<anonymous>:4:346490)
    at Function.getFilePath (<anonymous>:4:347760)
    at Function._load (<anonymous>:4:347855)
    at <anonymous>:4:351046
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at AsyncFunction.<anonymous> (<anonymous>:4:7155)

**Comment by White55Tiger** [comment]
I get the same error on WIndows 10.

Error: ENOENT: no such file or directory, lstat 'C:\Users\User\AppData\Local\Discord\app-1.0.9007\zlib'
    at Object.T [as realpathSync] (<anonymous>:4:346490)
    at Function.getFilePath (<anonymous>:4:347760)
    at Function._load (<anonymous>:4:347855)
    at <anonymous>:4:351046
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at AsyncFunction.<anonymous> (<anonymous>:4:7155)

**Comment by Lrive** [comment]
Exact same issue for me!

Error: ENOENT: no such file or directory, lstat 'C:\Users\lande\AppData\Local\Discord\app-1.0.9008\zlib'
    at Object.T [as realpathSync] (<anonymous>:4:346490)
    at Function.getFilePath (<anonymous>:4:347760)
    at Function._load (<anonymous>:4:347855)
    at <anonymous>:4:351046
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at AsyncFunction.<anonymous> (<anonymous>:4:7155)

**Comment by Miniontoby** [comment]
Please close this issue as the fix is inside:

https://github.com/Mega-Mewthree/BetterDiscordPlugins/issues/177#issuecomment-1664456294
