### ISSUE TITLE
Got a AutoStartRichPresence Error

### ISSUE THREAD

**Issue by Phoenix9225** [Mega-Mewthree/BetterDiscordPlugins#179]
An Error was encountered when i was loading the plugin. 

Error: ENOENT: no such file or directory, lstat 'C:\Users\calif\AppData\Local\Discord\app-1.0.9007\zlib'
at Object.T [as realpathSync] (:4:346490)
at Function.getFilePath (:4:347760)
at Function._load (:4:347855)
at :4:351046
at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
at Object.requireAddon (:4:39192)
at Object.loadAddon (:4:9163)
at Object.loadAddon (:4:36864)
at Object.reloadAddon (:4:10053)
at AsyncFunction. (:4:7189)

Is there any fix yet?

**Comment by fellowmean5** [comment]
no, plugin i outdated

**Comment by Taxrosdev** [comment]
I got ENOENT /usr/bin/zlib, using Arch Linux here

**Comment by Miniontoby** [comment]
Please close this issue as the fix is inside:

https://github.com/Mega-Mewthree/BetterDiscordPlugins/issues/177#issuecomment-1664456294
