### ISSUE TITLE
Could not be compiled

### ISSUE THREAD

**Issue by Wxtheredwxngs** [Mega-Mewthree/BetterDiscordPlugins#185]
Gives console with current message:
`**Error: ENOENT: no such file or directory, lstat 'C:\Users\Kino Fuzen\AppData\Local\Discord\app-1.0.9010\zlib'
    at Object.j [as realpathSync] (<anonymous>:4:340384)
    at Function.getFilePath (<anonymous>:4:341654)
    at Function._load (<anonymous>:4:341749)
    at <anonymous>:4:344940
    at eval **(betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)**
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at Object.requireAddon (<anonymous>:4:37112)
    at Object.loadAddon (<anonymous>:4:8234)
    at Object.loadAddon (<anonymous>:4:34784)
    at AsyncFunction.<anonymous> (<anonymous>:4:6226)**`

**Comment by Williamdotjpg** [comment]
Same here

**Comment by ContentLTD** [comment]
same

**Comment by EzSoftwares** [comment]
any solution guys

**Comment by Racooder** [comment]
Same here

**Comment by EternalRubis** [comment]
same here x)

**Comment by goldstargloww** [comment]
same issue
```
Error: ENOENT: no such file or directory, lstat 'C:\Users\**********\AppData\Local\Discord\app-1.0.9012\zlib'
    at Object.T [as realpathSync] (betterdiscord/renderer.js:4:324674)
    at L.getFilePath (betterdiscord/renderer.js:4:325944)
    at L._load (betterdiscord/renderer.js:4:326039)
    at betterdiscord/renderer.js:4:329230
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at A.requireAddon (betterdiscord/renderer.js:4:35265)
    at A.loadAddon (betterdiscord/renderer.js:4:7766)
    at A.loadAddon (betterdiscord/renderer.js:4:32937)
    at A.loadAllAddons (betterdiscord/renderer.js:4:10240)
    at A.initialize (betterdiscord/renderer.js:4:4662)
    at A.initialize (betterdiscord/renderer.js:4:32136)
    at Object.startup (betterdiscord/renderer.js:4:357163)

**Comment by SebJNZ** [comment]
Same here 😕

**Comment by Sultan0002** [comment]
Same issue
i think the plugin might be broken

**Comment by system-failure-b8xy** [comment]
To fix this issue on Windows, download and install [ZLib for Windows](https://gnuwin32.sourceforge.net/packages/zlib.htm) into the Discord folder. However, you may get another error after this one is fixed, such as `u.slice is not a function`.

**Comment by CrayzyEyezz** [comment]
> To fix this issue on Windows, download and install [ZLib for Windows](https://gnuwin32.sourceforge.net/packages/zlib.htm) into the Discord folder. However, you may get another error after this one is fixed, such as `u.slice is not a function`.

sick comment dude almost same effect as just creating a folder called zlip

it will not work anymore due to Discord making major internal changes in a recent silent update that restricted access to alot of stuff to plugins and that happend roughly Sep 2022

**Comment by Miniontoby** [comment]
Please close this issue as the fix is inside:

https://github.com/Mega-Mewthree/BetterDiscordPlugins/issues/177#issuecomment-1664456294
