### ISSUE TITLE
AutoStartRichPresence could not be compiled: ZLIB

### ISSUE THREAD

**Issue by Peiprjs** [Mega-Mewthree/BetterDiscordPlugins#189]
When trying to compile ASRP, the following error appears:
`Error: ENOENT: no such file or directory, lstat '/zlib'
at Object.T [as realpathSync] (betterdiscord/renderer.js:4:324533)
at L.getFilePath (betterdiscord/renderer.js:4:325803)
at L._load (betterdiscord/renderer.js:4:325898)
at betterdiscord/renderer.js:4:329089
at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
at A.requireAddon (betterdiscord/renderer.js:4:35124)
at A.loadAddon (betterdiscord/renderer.js:4:7625)
at A.loadAddon (betterdiscord/renderer.js:4:32796)
at A.loadAllAddons (betterdiscord/renderer.js:4:10099)
at A.initialize (betterdiscord/renderer.js:4:4521)
at A.initialize (betterdiscord/renderer.js:4:31995)
at Object.startup (betterdiscord/renderer.js:4:357022)`
**VERSIONS:**
- BD Core: 1.9.2
- ASRP: 2.0.6
- BDFDB: 3.2.8
- ZPL: 2.0.16

**Comment by Picsou06** [comment]
same

**Comment by PanDbEar** [comment]
same

**Comment by Beengoo** [comment]
The problem is that BetterDiscord has limited the use of some libraries, namely child-process and zlib
*Unfortunately, you can't fix it*

**Comment by ITProggeruz** [comment]
roses are red, errors are deaths

**Comment by Miniontoby** [comment]
I 'fixed' the plugin and uploaded it to betterdiscord website. Please consider reading:
https://github.com/Mega-Mewthree/BetterDiscordPlugins/issues/177#issuecomment-1664456294
