### ISSUE TITLE
could not compile

### ISSUE THREAD

**Issue by PellucidGames** [Mega-Mewthree/BetterDiscordPlugins#191]
Plugin did not compile, I do have the details on why not

`Error: ENOENT: no such file or directory, lstat 'C:\Users\refei\AppData\Local\Discord\app-1.0.9015\zlib'
    at Object.T [as realpathSync] (betterdiscord/renderer.js:4:327228)
    at L.getFilePath (betterdiscord/renderer.js:4:328498)
    at L._load (betterdiscord/renderer.js:4:328593)
    at betterdiscord/renderer.js:4:331784
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at M.requireAddon (betterdiscord/renderer.js:4:35818)
    at M.loadAddon (betterdiscord/renderer.js:4:8323)
    at M.loadAddon (betterdiscord/renderer.js:4:33490)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:6315)`

**Comment by ahaququq** [comment]
same

**Comment by Altiross** [comment]
same

**Comment by Miniontoby** [comment]
Please close this issue as the fix is inside:

https://github.com/Mega-Mewthree/BetterDiscordPlugins/issues/177#issuecomment-1664456294
