### ISSUE TITLE
Error, could not be compiled

### ISSUE THREAD

**Issue by Shingop** [Mega-Mewthree/BetterDiscordPlugins#192]
Console Details:

Error: ENOENT: no such file or directory, lstat '/zlib'
    at Object.T [as realpathSync] (betterdiscord/renderer.js:4:327228)
    at L.getFilePath (betterdiscord/renderer.js:4:328498)
    at L._load (betterdiscord/renderer.js:4:328593)
    at betterdiscord/renderer.js:4:331784
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at M.requireAddon (betterdiscord/renderer.js:4:35818)
    at M.loadAddon (betterdiscord/renderer.js:4:8323)
    at M.loadAddon (betterdiscord/renderer.js:4:33490)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:6315)

**Comment by codingMustache** [comment]
Close this issue. It is the same as #191
