### ISSUE TITLE
Yoohoo, you got an error

### ISSUE THREAD

**Issue by Hyperspeed-real** [Mega-Mewthree/BetterDiscordPlugins#195]
Error: 
ENOENT: 
no such file or directory, lstat 'C:\Users\[NAME]\AppData\Local\Discord\app-1.0.9018\zlib'
    at Object.T [as realpathSync] (betterdiscord/renderer.js:4:327228)
    at L.getFilePath (betterdiscord/renderer.js:4:328498)
    at L._load (betterdiscord/renderer.js:4:328593)
    at betterdiscord/renderer.js:4:331784
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at M.requireAddon (betterdiscord/renderer.js:4:35818)
    at M.loadAddon (betterdiscord/renderer.js:4:8323)
    at M.loadAddon (betterdiscord/renderer.js:4:33490)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:6315)
    
    my name's been replaced with [NAME] for obvious reasons, but you get the point. line errors maybe?

**Comment by Cipr3sso** [comment]
Adding the folder "zlib" gives another error: "TypeError: I.slice is not a function at betterdiscord/renderer.js:4:331784"; it looks like a betterdiscord problem. This plugin was made a year ago, so it may need an update by the author.

**Comment by CrayzyEyezz** [comment]
> Adding the folder "zlib" gives another error: "TypeError: I.slice is not a function at betterdiscord/renderer.js:4:331784"; it looks like a betterdiscord problem. This plugin was made a year ago, so it may need an update by the author.

it will not work anymore due to Discord making major internal changes in a recent silent update that restricted access to alot of stuff to plugins and that happend roughly Sep 2022

**Comment by Miniontoby** [comment]
Please close this issue as the fix is inside:

https://github.com/Mega-Mewthree/BetterDiscordPlugins/issues/177#issuecomment-1664456294

**Comment by Hyperspeed-real** [comment]
Thanks for fix! i did NOT expect a workaround two years later holy moly

**Comment by Miniontoby** [comment]
It has already been out for like one and a half years now...

But yeah I decided to tell everyone now again, since this repo is officially no longer getting supported anymore...
And also since I had nothing else better to do
