### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BozydarBelkot** [Mega-Mewthree/BetterDiscordPlugins#197]
Error: ENOENT: no such file or directory, lstat 'C:\Users\nomar\AppData\Local\Discord\app-1.0.9026\zlib'
    at Object.realpathSync (betterdiscord/renderer.js:5:331452)
    at p.getFilePath (betterdiscord/renderer.js:5:333151)
    at p._load (betterdiscord/renderer.js:5:333246)
    at betterdiscord/renderer.js:5:336308
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at A.requireAddon (betterdiscord/renderer.js:5:34905)
    at A.loadAddon (betterdiscord/renderer.js:5:7343)
    at A.loadAddon (betterdiscord/renderer.js:5:32573)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:5:5323)

**Comment by Miniontoby** [comment]
Please close this issue as the fix is inside:

https://github.com/Mega-Mewthree/BetterDiscordPlugins/issues/177#issuecomment-1664456294
