### ISSUE TITLE
An error occoured while trying to compile

### ISSUE THREAD

**Issue by XDPXI** [Mega-Mewthree/BetterDiscordPlugins#199]
Error: ENOENT: no such file or directory, lstat 'C:\Users\xavie\AppData\Local\DiscordPTB\app-1.0.1051\zlib'
    at Object.realpathSync (betterdiscord/renderer.js:5:336446)
    at p.getFilePath (betterdiscord/renderer.js:5:338145)
    at p._load (betterdiscord/renderer.js:5:338240)
    at betterdiscord/renderer.js:5:341345
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at A.requireAddon (betterdiscord/renderer.js:5:33832)
    at A.loadAddon (betterdiscord/renderer.js:5:6386)
    at A.loadAddon (betterdiscord/renderer.js:5:31500)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:5:4366)

**Comment by Miniontoby** [comment]
Please close this issue as the fix is inside:

https://github.com/Mega-Mewthree/BetterDiscordPlugins/issues/177#issuecomment-1664456294
