### ISSUE TITLE
AutoStartRichPresence could not be compiled.

### ISSUE THREAD

**Issue by system-failure-b8xy** [Mega-Mewthree/BetterDiscordPlugins#202]
After fixing my earlier problem of the missing zlib folder by installing Zlib into my Discord folder, I now have a new problem:

![image](https://github.com/Mega-Mewthree/BetterDiscordPlugins/assets/89991471/70a2f8e2-2ce0-4313-9355-f833fa9ae2c6)
```
TypeError: u.slice is not a function
    at p.resolveMainFile (betterdiscord/renderer.js:5:337851)
    at p._load (betterdiscord/renderer.js:5:338441)
    at betterdiscord/renderer.js:5:341345
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at A.requireAddon (betterdiscord/renderer.js:5:33832)
    at A.loadAddon (betterdiscord/renderer.js:5:6386)
    at A.loadAddon (betterdiscord/renderer.js:5:31500)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:5:4366)
```

**Comment by Miniontoby** [comment]
The zlib doesn't work

Please close this issue as the fix is inside:
https://github.com/Mega-Mewthree/BetterDiscordPlugins/issues/177#issuecomment-1664456294
