### ISSUE TITLE
RIch Presence Plugin Could not be compiled.

### ISSUE THREAD

**Issue by Jerome4-arc** [Mega-Mewthree/BetterDiscordPlugins#205]
Error: ENOENT: no such file or directory, lstat '/zlib'
    at Object.realpathSync (betterdiscord/renderer.js:5:370182)
    at p.getFilePath (betterdiscord/renderer.js:5:371881)
    at p._load (betterdiscord/renderer.js:5:371976)
    at betterdiscord/renderer.js:5:375069
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at N.requireAddon (betterdiscord/renderer.js:5:28792)
    at N.loadAddon (betterdiscord/renderer.js:5:6412)
    at N.loadAddon (betterdiscord/renderer.js:5:26460)
    at betterdiscord/renderer.js:5:4392

Do we need a diffrent lib or is there something wrong with the .js file?

**Comment by Yeastdonkey** [comment]
Same
```
Error: ENOENT: no such file or directory, lstat 'C:\Users\REDACTED\AppData\Local\Discord\app-1.0.9161\zlib'
    at Object.realpathSync (betterdiscord/renderer.js:5:369923)
    at p.getFilePath (betterdiscord/renderer.js:5:371622)
    at p._load (betterdiscord/renderer.js:5:371717)
    at betterdiscord/renderer.js:5:374810
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:104:18)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2014:6)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:2273:5)
    at eval (betterdiscord://plugins/AutoStartRichPresence.plugin.js:3729:3)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201
```

**Comment by Miniontoby** [comment]
Please close this issue as the fix is inside:
https://github.com/Mega-Mewthree/BetterDiscordPlugins/issues/177#issuecomment-1664456294
